# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0002_page-templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghu_main.Page')),
            ],
        ),
    ]
