# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0003_toolkit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolkit',
            name='pages',
        ),
        migrations.AddField(
            model_name='toolkit',
            name='pages',
            field=models.ManyToManyField(to='ghu_main.Page'),
        ),
    ]
