# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ghu_main', '0003_toolkit'), ('ghu_main', '0004_auto_20170916_1857'), ('ghu_main', '0005_auto_20170922_1836')]

    dependencies = [
        ('ghu_main', '0003_Navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghu_main.Page')),
                ('toolkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghu_main.Toolkit')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
