# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0004_auto_20170916_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolkitPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghu_main.Page')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='toolkit',
            name='pages',
        ),
        migrations.AddField(
            model_name='toolkitpage',
            name='toolkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghu_main.Toolkit'),
        ),
    ]
