# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0005_navbar_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarentry',
            options={'ordering': ('order',), 'verbose_name': 'Navigation bar entry', 'verbose_name_plural': 'Navigation bar entries'},
        ),
        migrations.RenameField(
            model_name='toolkit',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='toolkit',
            name='slug',
            field=models.SlugField(default='toolkit', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolkit',
            name='summary',
            field=models.TextField(default='(summary)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolkitpage',
            name='contents',
            field=models.TextField(default='(contents)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolkitpage',
            name='slug',
            field=models.SlugField(default='toolkitpage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolkitpage',
            name='title',
            field=models.CharField(default='(title)', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toolkitpage',
            name='toolkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ghu_main.Toolkit'),
        ),
        migrations.RemoveField(
            model_name='toolkitpage',
            name='page',
        ),
        migrations.AlterUniqueTogether(
            name='toolkitpage',
            unique_together=set([('toolkit', 'slug')]),
        ),
    ]
