# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0006_toolkit_rewework'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProfileTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='User-friendly title')),
                ('template', models.CharField(max_length=256, verbose_name='Template to execute')),
            ],
        ),
    ]
