# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-17 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0008_orgprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgProfileTemplate',
        ),
    ]
