# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0011_auto_20171018_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgprofile',
            name='location',
        ),
    ]
