# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0012_remove_orgprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
