# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0013_orgprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgprofile',
            name='summary',
            field=models.CharField(default='Summary', max_length=256),
        ),
    ]
