# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghu_main', '0014_orgprofile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='summary',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
