# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToolkitSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('visible', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ghu_toolkits.ToolkitSection', related_name='children')),
            ],
        ),
        migrations.AddField(
            model_name='toolkit',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghu_toolkits.ToolkitSection'),
        ),
    ]
